In [2]:
import pandas as pd
import numpy as np

In [3]:
# Input Dataset
data_input = {
    "Document": ["D1", "D2", "D3", "D4"],
    "text": [
        "people watch campusx",
        "campusx watch campusx",
        "people write comment",
        "campusx write comment"
    ],
    "output": [1, 1, 0, 0]
}

In [4]:
df = pd.DataFrame(data_input)

In [5]:
df

,Document,text,output
0,D1,people watch campusx,1
1,D2,campusx watch campusx,1
2,D3,people write comment,0
3,D4,campusx write comment,0


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(df['text'])

In [8]:
# vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [9]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [11]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)